(() => {
  "use strict";
  const $ = id => document.getElementById(id);
  const escapeHtml = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const palettes = {
    percent:[[15,"#7a1515"],[20,"#bd3b28"],[25,"#e9813f"],[30,"#efba54"],[35,"#f1df8a"],[100,"#e2e8e4"]],
    heatrisk:[[1,"#fee08b"],[2,"#fdae61"],[3,"#f46d43"],[4,"#a50026"]],
    wind:[[20,"#d6e8f0"],[30,"#9bc8db"],[40,"#559fbd"],[50,"#26769c"],[100,"#174963"]],
    cold:[[-20,"#303b88"],[0,"#4669b2"],[10,"#6e9ed0"],[25,"#aad3e8"],[100,"#e3edf2"]],
    snow:[[1,"#dcd3f3"],[3,"#a98bd7"],[6,"#7452ae"],[100,"#432371"]],
    ice:[[.1,"#d8f0f0"],[.25,"#70c4c2"],[.5,"#228c89"],[100,"#0c514f"]],
    visibility:[[.25,"#5b6470"],[1,"#9da5ad"],[100,"#dde1e4"]],
    categorical:[[0,"#d8e0db"],[1,"#88a99a"],[2,"#32745a"],[3,"#164934"],[99,"#6c7880"]]
  };
  const metric=(id,label,value,unit,palette="categorical",rule="",format=null)=>({id,label,value,unit,palette,rule,format});
  const publicFixed=(summary,metrics,source="ZASNet automation configuration",note="National screening value; local NWS criteria can differ.")=>({zoneType:"public",summary,metrics,source,note});
  const fireBase={zoneType:"fire",summary:"Regional fire screening uses either zone-wide wind/low-RH criteria or an SPC dry-thunder outlook overlapping the exact NWS product and fire zone.",source:"Operational ZASNet regional profiles · official operating plans · NOAA/SPC fire outlooks",note:"Wind and gust are alternatives. Dry-thunder support requires temporal and polygon overlap with the exact NWS fire product. Fuels remain supplied by that exact NWS/partner confirmation.",metrics:[metric("rh","Maximum relative humidity","Regional","%","percent","Hourly zone-minimum RH must be at or below the printed value for the wind/RH pathway."),metric("wind","Minimum sustained wind","Regional","mph","Zone-maximum sustained wind may satisfy the wind branch."),metric("gust","Minimum wind gust","Regional","mph","Zone-maximum gust may satisfy the alternate gust branch."),metric("duration","Required duration","Regional","hours","The printed number of qualifying hours must occur inside the printed time window; an overlapping SPC dry-thunder outlook is an alternate pathway.")]};
  const marine=(summary,metrics)=>({zoneType:"marine",summary,metrics,source:"Current ZASNet marine automation profiles",note:"Great Lakes and ocean zones use different small-craft wave thresholds; storm and hurricane-force wind gates are national."});
  const local=(zoneType,summary,label="Local or station threshold")=>({zoneType,summary,source:"Local/station-dependent criteria",note:"The current automation does not encode one valid nationwide numeric threshold for this product.",metrics:[metric("local",label,"Local / station","","categorical","Consult the controlling station threshold or local operating plan.")]});
  const catalog={
    "Criteria sectors":{zoneType:"public",summary:"Seven national sectors organize criteria research and regional threshold profiles.",source:"ZASNet seven-sector criteria framework",note:"Heavy black sector boundaries are the top overlay on every criteria map.",metrics:[metric("combined","Sector framework","1–7","","categorical","Seven numbered criteria research sectors.")]},
    "Red Flag Warning":{...fireBase},"Fire Weather Watch":{...fireBase,summary:"Potential critical fire weather using the same ingredient screen, with watch timing confirmed separately."},
    "Heat Advisory":publicFixed("Elevated heat impacts represented by the NWS/WPC HeatRisk category.",[metric("heatrisk","Minimum HeatRisk",2," · Major","heatrisk","At least HeatRisk category 2 during the alert period.")]),
    "Extreme Heat Watch":publicFixed("Potential major to extreme heat impacts represented by HeatRisk.",[metric("heatrisk","Minimum HeatRisk",3," · Major","heatrisk","At least HeatRisk category 3 during the alert period; watch confidence comes from the confirming product.")]),
    "Extreme Heat Warning":publicFixed("Major to extreme heat impacts represented by HeatRisk.",[metric("heatrisk","Minimum HeatRisk",3," · Major","heatrisk","At least HeatRisk category 3 during the alert period.")]),
    "Wind Advisory":{...publicFixed("Proposed regional thresholds for strong non-convective wind below warning level.",[metric("sustained","Minimum sustained wind","Regional","mph","wind","Sustained wind for at least one hour, or the gust criterion."),metric("gust","Minimum frequent gust","Regional","mph","wind","Gulf/Florida and parts of the Southeast use lower advisory gust thresholds; exposed western mountain zones suppress this tier.")],"Proposed from official NWS WFO criteria research","Review map only; the operational wind backend remains unchanged."),proposed:true},
    "High Wind Watch":{...publicFixed("Proposed regional thresholds for potential damaging non-convective wind.",[metric("sustained","Minimum sustained wind","Regional","mph","wind","At least one hour; exposed western mountain zones use 50 mph."),metric("gust","Minimum frequent gust","Regional","mph","wind","Most zones use 58 mph; exposed western mountain zones use 75 mph.")],"Proposed from official NWS WFO criteria research","Review map only. Watch confidence comes from the exact NWS product, not a different speed."),proposed:true},
    "High Wind Warning":{...publicFixed("Proposed regional thresholds for damaging non-convective wind.",[metric("sustained","Minimum sustained wind","Regional","mph","wind","At least one hour; exposed western mountain zones use 50 mph."),metric("gust","Minimum frequent gust","Regional","mph","wind","Most zones use 58 mph; exposed western mountain zones use 75 mph.")],"Proposed from official NWS WFO criteria research","Review map only; the operational wind backend remains unchanged."),proposed:true},
    "Cold Weather Advisory":{...publicFixed("Proposed regional thresholds for dangerous cold below warning level.",[metric("temperature","Maximum temperature or apparent temperature","Regional","°F","cold","Either actual temperature or apparent temperature may qualify."),metric("duration","Required duration","Regional","hours","categorical","Proposed duration varies from two to four hours by regional profile.")],"Proposed from official NWS WFO cold-criteria research","Review map only; the operational cold backend remains unchanged."),proposed:true},
    "Extreme Cold Watch":{...publicFixed("Proposed regional thresholds for possible extreme cold.",[metric("temperature","Maximum temperature or apparent temperature","Regional","°F","cold","Either actual temperature or apparent temperature may qualify."),metric("duration","Required duration","Regional","hours","categorical","Watch confidence comes from the exact NWS product.")],"Proposed from official NWS WFO cold-criteria research","Review map only; the operational cold backend remains unchanged."),proposed:true},
    "Extreme Cold Warning":{...publicFixed("Proposed regional thresholds for extreme cold.",[metric("temperature","Maximum temperature or apparent temperature","Regional","°F","cold","Either actual temperature or apparent temperature may qualify."),metric("duration","Required duration","Regional","hours","categorical","Proposed duration varies from two to four hours by regional profile.")],"Proposed from official NWS WFO cold-criteria research","Review map only; the operational cold backend remains unchanged."),proposed:true},
    "Freeze Watch":publicFixed("Potential growing-season freeze.",[metric("temperature","Maximum minimum temperature",32,"°F","cold","Forecast minimum at or below freezing during the configured growing season.")]),
    "Freeze Warning":publicFixed("Growing-season freeze.",[metric("temperature","Maximum minimum temperature",32,"°F","cold","Forecast minimum at or below freezing during the configured growing season.")]),
    "Winter Weather Advisory":{...publicFixed("Proposed regional/elevation thresholds for impactful snow or sub-warning ice.",[metric("snow","Minimum 24-hour snow","Regional","in","snow","Regional and terrain-dependent snow accumulation."),metric("ice","Maximum advisory ice","Regional","in","ice","Any road icing may warrant an advisory; map displays the warning boundary.")],"Official WFO winter criteria research","Review only; western mountain and lowland zones are separated and winter remains disabled."),proposed:true},
    "Winter Storm Watch":{...publicFixed("Potential to meet regional/elevation Winter Storm Warning criteria.",[metric("snow12","Minimum 12-hour snow","Regional","in","snow","Regional and terrain-dependent 12-hour accumulation."),metric("snow24","Minimum 24-hour snow","Regional","in","snow","Regional and terrain-dependent 24-hour accumulation."),metric("ice","Minimum warning ice","Regional","in","ice","Predominantly freezing-rain events may instead use Ice Storm Warning.")],"Official WFO winter criteria research","Review only. Watch probability/timing comes from the exact NWS product; winter remains disabled."),proposed:true},
    "Winter Storm Warning":{...publicFixed("Regional/elevation thresholds for significant winter storms.",[metric("snow12","Minimum 12-hour snow","Regional","in","snow","Regional and terrain-dependent 12-hour accumulation."),metric("snow24","Minimum 24-hour snow","Regional","in","snow","Regional and terrain-dependent 24-hour accumulation."),metric("ice","Minimum warning ice","Regional","in","ice","Predominantly freezing-rain events may instead use Ice Storm Warning.")],"Official WFO winter criteria research","Review only; mixed sleet/impact exceptions require additional evidence and winter remains disabled."),proposed:true},
    "Ice Storm Warning":{...publicFixed("Damaging ice accretion when freezing rain is the predominant winter hazard.",[metric("ice","Minimum ice accumulation","Regional","in","ice","Most zones use 0.25 inch; parts of the Northeast use 0.50 inch. The threshold generally applies over a substantial portion of the zone or its population center.")],"Official NWS/WFO Ice Storm Warning criteria","Review only. Mixed snow/sleet/ice normally uses Winter Storm Warning; Alaska may use Winter Storm Warning for cold-ground freezing rain. Winter remains disabled."),proposed:true},
    "Blizzard Warning":publicFixed("Life-threatening whiteout conditions from falling or blowing snow.",[metric("wind","Minimum sustained wind or frequent gust",35,"mph","wind","Sustained wind or frequent gusts at or above 35 mph."),metric("snow","Falling or blowing snow","Required","","categorical","Falling snow or previously fallen snow capable of being blown; no new accumulation minimum is required."),metric("visibility","Maximum visibility",.25,"mi","visibility","Visibility frequently at or below one quarter mile."),metric("duration","Required duration",3,"hours","categorical","All blizzard conditions persist for at least three hours.")],"National NWS Blizzard Warning criteria","All four requirements must occur together. Wind alone never qualifies; winter automation remains disabled."),
    "Dense Fog Advisory":publicFixed("Visibility severely reduced by fog.",[metric("visibility","Maximum visibility",.25,"mi","visibility","NDFD or fresh RTMA visibility at or below one quarter mile.")]),
    "Freezing Fog Advisory":publicFixed("Freezing fog with very low visibility.",[metric("visibility","Maximum visibility",1,"mi","visibility","Freezing-fog signal, temperature at or below 32°F, and visibility at or below one mile.")]),
    "Dense Smoke Advisory":publicFixed("Visibility severely reduced by smoke.",[metric("visibility","Maximum visibility",.25,"mi","visibility","Smoke visibility at or below one quarter mile.")]),
    "Blowing Dust Advisory":publicFixed("Visibility reduced by blowing dust.",[metric("visibility","Maximum visibility",1,"mi","visibility","Visibility above 0.25 and at or below one mile.")]),
    "Dust Storm Warning":publicFixed("Near-zero visibility in blowing dust.",[metric("visibility","Maximum visibility",.25,"mi","visibility","Visibility at or below one quarter mile, with wind or gust at least 25 mph."),metric("wind","Minimum wind or gust",25,"mph","wind","Wind component of the screen.")]),
    "Flood Watch":publicFixed("Rainfall-driven flooding threat; non-rainfall causes fail closed.",[metric("ero","Minimum WPC ERO risk",1," · Marginal","heatrisk","All are required: exact active NWS Flood Watch for the zone, NWS text explicitly identifies rainfall, fresh positive zone-wide NDFD QPF during the watch, and overlapping WPC Marginal Risk or higher.")],"National NWS Flood Watch guidance + WPC ERO + NDFD QPF","No universal rainfall amount is encoded. Rainfall-driven watches remain eligible when burn scars or debris flows are also mentioned. Dam/levee failure, ice jams, snowmelt, burn-scar-only threats, unsupported river flooding, and unknown causes are excluded. The map shows the only geographic threshold: WPC ERO category."),
    "Coastal Flood Advisory":{zoneType:"public",summary:"Forecast total water level reaches the controlling NOAA CO-OPS minor flood threshold during the advisory window.",source:"NOAA CO-OPS NWS/NOS station flood levels and observations",note:"Station-datum thresholds are converted to MLLW before comparison.",metrics:[metric("local","Controlling minor flood level","Station-specific","MLLW","categorical","Fresh observed tidal anomaly is added to tide predictions during the exact product period.")]},
    "Coastal Flood Watch":{zoneType:"public",summary:"Forecast total water level reaches the controlling NOAA CO-OPS moderate flood threshold during the watch window.",source:"NOAA CO-OPS NWS/NOS station flood levels and observations",note:"Watch identity and confidence come from the exact active NWS product; the independent water-level threshold must also pass.",metrics:[metric("local","Controlling moderate flood level","Station-specific","MLLW","categorical","Fresh observed tidal anomaly is added to tide predictions during the exact product period.")]},
    "Coastal Flood Warning":{zoneType:"public",summary:"Forecast total water level reaches the controlling NOAA CO-OPS moderate flood threshold during the warning window.",source:"NOAA CO-OPS NWS/NOS station flood levels and observations",note:"Major flooding remains the same warning product with stronger impact wording.",metrics:[metric("local","Controlling moderate flood level","Station-specific","MLLW","categorical","Fresh observed tidal anomaly is added to tide predictions during the exact product period.")]},
    "Lakeshore Flood Advisory":local("public","Minor lakeshore flooding using locally defined criteria."),"Lakeshore Flood Watch":local("public","Potential significant lakeshore flooding using locally defined criteria."),"Lakeshore Flood Warning":local("public","Significant lakeshore flooding using locally defined criteria."),
    "High Surf Advisory":local("public","High surf using locally defined breaking-wave criteria."),"High Surf Warning":local("public","Dangerously high surf using locally defined breaking-wave criteria."),"Rip Current Statement":local("public","Elevated rip-current risk using beach and local-office criteria."),"Beach Hazards Statement":local("public","Locally defined dangerous beach conditions."),"Coastal Hazard Statement":local("public","Locally defined shoreline hazards."),"Lakeshore Hazard Statement":local("public","Locally defined lakeshore hazards."),
    "Small Craft Advisory":marine("Conditions hazardous to small craft.",[metric("wind","Minimum wind",z=>z.greatLakes?22:21,"kt","wind","Great Lakes: 22 kt; ocean profile: 21 kt. Wave criteria may independently qualify."),metric("waves","Minimum wave height",z=>z.greatLakes?4:10,"ft","snow","Great Lakes: greater than 4 ft; ocean profile: 10 ft.")]),
    "Gale Watch":marine("Potential gale-force wind.",[metric("wind","Minimum wind",34,"kt","wind","Watch confidence is provided separately.")]),"Gale Warning":marine("Gale-force wind.",[metric("wind","Minimum wind",34,"kt","wind","Sustained wind or gust screen.")]),
    "Storm Watch":marine("Potential storm-force wind.",[metric("wind","Minimum wind",48,"kt","wind","Watch confidence is provided separately.")]),"Storm Warning":marine("Storm-force wind.",[metric("wind","Minimum wind",48,"kt","wind","Sustained wind or gust screen.")]),
    "Hurricane Force Wind Watch":marine("Potential hurricane-force marine wind.",[metric("wind","Minimum wind",64,"kt","wind","Watch confidence is provided separately.")]),"Hurricane Force Wind Warning":marine("Hurricane-force marine wind.",[metric("wind","Minimum wind",64,"kt","wind","Sustained wind or gust screen.")]),
    "Dense Fog Advisory (Marine)":marine("Marine visibility reduced by fog.",[metric("visibility","Maximum visibility",1,"mi","visibility","Forecast marine visibility at or below one mile.")]),
    "Air Quality Alert":local("county","Agency-issued air-quality criteria and reporting-area confirmation.","AirNow / state agency determination")
  };
  const groups={"Map framework":["Criteria sectors"],"Fire weather":["Red Flag Warning","Fire Weather Watch"],"Heat":["Heat Advisory","Extreme Heat Watch","Extreme Heat Warning"],"Wind and cold":["Wind Advisory","High Wind Watch","High Wind Warning","Cold Weather Advisory","Extreme Cold Watch","Extreme Cold Warning","Freeze Watch","Freeze Warning"],"Winter":["Winter Weather Advisory","Winter Storm Watch","Winter Storm Warning","Ice Storm Warning","Blizzard Warning"],"Visibility and air":["Dense Fog Advisory","Freezing Fog Advisory","Dense Smoke Advisory","Blowing Dust Advisory","Dust Storm Warning","Air Quality Alert"],"Flood and coast":["Flood Watch","Coastal Flood Advisory","Coastal Flood Watch","Coastal Flood Warning","Lakeshore Flood Advisory","Lakeshore Flood Watch","Lakeshore Flood Warning","High Surf Advisory","High Surf Warning","Rip Current Statement","Beach Hazards Statement","Coastal Hazard Statement","Lakeshore Hazard Statement"],"Marine":["Small Craft Advisory","Gale Watch","Gale Warning","Storm Watch","Storm Warning","Hurricane Force Wind Watch","Hurricane Force Wind Warning","Dense Fog Advisory (Marine)"]};
  const zoneLabels={public:"Public forecast zones",fire:"Fire-weather zones",marine:"Coastal and Great Lakes marine zones",county:"County areas"};
  const displayValue=(m,value)=>m.format?m.format(value):typeof value==="number"?`${Number.isInteger(value)?value:value.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')} ${m.unit}`.trim():String(value);
  const hashFor=name=>`#${encodeURIComponent(name.toLowerCase().replace(/\s+/g,"-"))}`;
  const hazardFromHash=()=>{const slug=decodeURIComponent(location.hash.slice(1)).toLowerCase();return Object.keys(catalog).find(name=>name.toLowerCase().replace(/\s+/g,"-")===slug)||"Criteria sectors"};
  function render({updateHash=true}={}){const hazard=$("hazardSelect").value,spec=catalog[hazard],draft=Boolean(spec.staticImage),proposed=Boolean(spec.proposed),review=draft||proposed,combinedRule=hazard==="Criteria sectors"?"Seven numbered national sectors":spec.metrics.map(m=>m.rule).filter(Boolean).join(" "),image=$("criteriaMapImage");if(updateHash&&location.hash!==hashFor(hazard))history.pushState(null,"",hashFor(hazard));document.title=`${hazard} criteria · ZASNet`;$("hazardTitle").textContent=hazard;$("hazardSummary").textContent=spec.summary;$("metricLabel").textContent=review?"Status":hazard==="Criteria sectors"?"Framework":"Combined criteria";$("metricValue").textContent=review?"Review only":hazard==="Criteria sectors"?"Sectors 1–7":"All required values";$("criteriaRule").textContent=combinedRule;$("sourceName").textContent=spec.source;$("sourceNote").textContent=spec.note;$("mapZoneType").textContent=proposed?`${zoneLabels[spec.zoneType]} · proposed`:draft?"Fire-weather zones · proposed":hazard==="Criteria sectors"?"National sector framework":zoneLabels[spec.zoneType];$("mapHeading").textContent=review?"Proposed regional profiles":hazard==="Criteria sectors"?"Color-coded sectors 1–7":"Combined criteria profile";$("legend").innerHTML=`<div class="legend-row"><span>${review?"Proposed thresholds for review; not used by live automation.":"Every required value is printed together on the map image."}</span></div>`;$("mapStatus").hidden=false;$("mapStatus").textContent=review?"Loading proposed map…":"Rendering combined criteria map…";$("imageError").hidden=true;image.alt=`${hazard} combined criteria map`;image.src=draft?spec.staticImage:`/api/public/criteria-map.png?hazard=${encodeURIComponent(hazard)}&metric=combined`;}
  function initSelect(){for(const[group,names]of Object.entries(groups)){const optgroup=document.createElement("optgroup");optgroup.label=group;for(const name of names)if(catalog[name])optgroup.append(new Option(name,name));$("hazardSelect").append(optgroup)}$("hazardSelect").value=hazardFromHash();$("hazardSelect").addEventListener("change",()=>render());window.addEventListener("hashchange",()=>{const hazard=hazardFromHash();if($("hazardSelect").value!==hazard){$("hazardSelect").value=hazard;render({updateHash:false})}});render({updateHash:!location.hash})}
  $("criteriaMapImage").addEventListener("load",()=>{$("mapStatus").hidden=true;$("imageError").hidden=true});$("criteriaMapImage").addEventListener("error",()=>{$("mapStatus").hidden=true;$("imageError").hidden=false;$("imageError").textContent="This criteria map could not be rendered. Try another product or reload the page."});initSelect();
})();
