(() => {
  const model = () => document.querySelector("#modelSelect")?.value || "ncep";
  const run = () => document.querySelector("#runSelect")?.selectedOptions[0]?.value || "";
  const product = () => document.querySelector("#activeProductName")?.textContent || "Model product";
  const productId = () => document.querySelector(".product-card.is-selected")?.dataset.product || "";
  const host = document.querySelector(".map-workspace"); if (!host) return;
  const legend = document.createElement("aside"); legend.id = "gfeLegend"; legend.className = "gfe-legend"; legend.innerHTML = "<span>Loading legend…</span>"; host.append(legend);
  const esc = (value) => String(value ?? "").replace(/[&<>\"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]));
  async function loadLegend() { const source = model(), id = productId(), selectedRun = run(); if (!id) return; legend.innerHTML = "<span>Loading legend…</span>"; try { const latest = await fetch(`/api/public/models/${source}/latest.json`, { cache: "no-store" }).then((response) => response.json()); const catalog = (latest.runs || [latest]).find((entry) => String(entry.run) === selectedRun) || latest.runs?.[0] || latest; const modelId = source === "ncep" ? `znws-wrf-${String(catalog.domain || "MESO1").toLowerCase()}` : source; const frames = await fetch(`/v1/models/${encodeURIComponent(modelId)}/${encodeURIComponent(catalog.run)}/${encodeURIComponent(id)}/frames`, { cache: "force-cache" }).then((response) => { if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }); const info = frames.product || frames, palette = Array.isArray(info.palette) ? info.palette : [], values = palette.map((entry) => entry.value ?? entry.label ?? ""), colors = palette.map((entry) => entry.color || "#718096"); legend.innerHTML = `<div class="gfe-legend-head"><strong>${esc(product())}</strong><span>${esc(info.unit || "Model guidance")}</span></div><div class="gfe-legend-ramp" style="background:linear-gradient(90deg,${colors.join(",")})"></div><div class="gfe-legend-values">${values.map((value) => `<span>${esc(value)}</span>`).join("")}</div>`; } catch (error) { legend.innerHTML = `<span>Legend unavailable · ${esc(error.message)}</span>`; } }
  ["change", "input"].forEach((eventName) => document.addEventListener(eventName, (event) => { if (["modelSelect", "runSelect", "hourSelect"].includes(event.target?.id) || event.target?.closest(".product-card")) window.setTimeout(loadLegend, 80); }));
  const observer = new MutationObserver(() => window.setTimeout(loadLegend, 80)); observer.observe(document.querySelector("#activeProductName"), { childList: true, characterData: true, subtree: true }); loadLegend();
})();
